"""
Django settings for rec_sys_prj project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'static')
MEDIA_DIR = os.path.join(BASE_DIR, 'media')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$lrs_@d(hw3^1jftz-f^s2ruc()7egcih#6pq(u@()lxa13y3n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rec_sys_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.TokenAuthentication',),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated', )
}

ROOT_URLCONF = 'rec_sys_prj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rec_sys_prj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# token: c6f02775276bdcdac8320482013f21589f2cd737

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
# DATABASES = {
#     'default': {
#         # 'ENGINE': 'django.db.backends.postgresql',
#         # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     },
#     'auth_db': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'HOST': "auth-db.c84mfrwjherq.us-east-1.rds.amazonaws.com",
#         "PORT": 5432,
#         'NAME': 'auth_db',
#         'USER': 'postgresql_user',
#         'PASSWORD': '59CZj6BhdLV!M7K',
#     },
#     'primary1': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'HOST': "primary1.c84mfrwjherq.us-east-1.rds.amazonaws.com",
#         "PORT": 5432,
#         'NAME': 'primary1',
#         'USER': 'primary1',
#         'PASSWORD': '4CD7GsYh8FpC4!D',
#     },
#     'replica1': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'HOST': "replica1.c84mfrwjherq.us-east-1.rds.amazonaws.com",
#         "PORT": 5432,
#         'NAME': 'replica1',
#         'USER': 'replica1',
#         'PASSWORD': '3feJz6iER7QeNGF',
#     },
#     'replica2': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'HOST': "replica2.c84mfrwjherq.us-east-1.rds.amazonaws.com",
#         "PORT": 5432,
#         'NAME': 'replica2',
#         'USER': 'replica2',
#         'PASSWORD': 'cjCyh2GRz5CvD!k',
#     },
# }

# # path.to.Routers
# PrimaryReplicaRouter_DIR = 'utils.primaryreplicarouter.PrimaryReplicaRouter'
# AuthRouter_DIR = 'utils.authrouter.AuthRouter'
# DATABASE_ROUTERS = [AuthRouter_DIR, PrimaryReplicaRouter_DIR]

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [     # can not be changed.
    STATIC_DIR,
]

# MEDIA INFORMATION:
MEDIA_URL = "/media/"
MEDIA_ROOT = MEDIA_DIR
